#!/usr/bin/env python3
r"""Generate the broad-corpus fidelity LaTeX table (paper Table~5).

Reads eval_multigame.npz from the v3 (encoder-only) and v3+dec
(joint-decoder) Train-94 runs, computes mean / median per-cell rollout
cell-error across the 94 games for each rollout regime, and writes a
LaTeX fragment for \input.

Output: nca_wm/paper/figures/fidelity/{table.tex, summary.json}

Usage:
    .venv/bin/python3 nca_wm/scripts/collate_fidelity_table.py
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
LOGS_ROOT = REPO_ROOT / "nca_wm" / "logs"
OUT_DIR = REPO_ROOT / "nca_wm" / "paper" / "figures" / "fidelity"

# (run_dir, label, latex_label) — rows in the output table follow this order.
RUNS = [
    ("multi_scaling_gallery_v3", "encoder_only",
     r"\textsc{Train-94} (encoder-only, $\beta = 0$)"),
    ("multi_scaling_gallery_v3_decoder", "joint_decoder",
     r"\textsc{Train-94} (joint decoder, $\beta = 1.0$)"),
]

# (algo key, display label) — columns in the output table.
REGIMES = [
    ("random", "random (AR)"),
    ("random_tf", "1-step (TF)"),
    ("bfs", "BFS (oracle)"),
    ("astar", "A* (oracle)"),
]


_KEY_RE = re.compile(r"^(?P<game>.+?)_L(?P<level>\d+)_(?P<algo>random_tf|random|bfs|astar)_cell_error_rate$")


def _aggregate(eval_npz: Path) -> dict:
    if not eval_npz.exists():
        raise FileNotFoundError(eval_npz)
    d = np.load(eval_npz, allow_pickle=True)
    per_algo: dict[str, dict[str, list[float]]] = {a: {} for a, _ in REGIMES}
    for key in d.files:
        m = _KEY_RE.match(key)
        if m is None:
            continue
        algo = m.group("algo")
        if algo not in per_algo:
            continue
        arr = np.asarray(d[key], dtype=np.float64).ravel()
        if arr.size == 0:
            continue
        per_algo[algo].setdefault(m.group("game"), []).append(float(arr.mean()))
    out = {}
    for algo, _ in REGIMES:
        per_game_means = [float(np.mean(v)) for v in per_algo[algo].values()]
        if not per_game_means:
            out[algo] = None
        else:
            out[algo] = {
                "n_games": len(per_game_means),
                "mean": float(np.mean(per_game_means)),
                "median": float(np.median(per_game_means)),
            }
    return out


def _fmt(stat: dict | None) -> str:
    if stat is None:
        return "--"
    return f"{100*stat['mean']:.2f}\\% / {100*stat['median']:.2f}\\%"


def write_table(rows: list[tuple[str, dict]], out_path: Path) -> None:
    col_spec = "l " + " ".join(["c"] * len(REGIMES))
    lines = [
        "% AUTOGENERATED by nca_wm/scripts/collate_fidelity_table.py — do not edit.",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "  \\toprule",
        "  Model & " + " & ".join(label for _, label in REGIMES) + r" \\",
        "  & " + " & ".join([r"\small mean / median"] * len(REGIMES)) + r" \\",
        "  \\midrule",
    ]
    for label, results in rows:
        cells = [_fmt(results.get(algo)) for algo, _ in REGIMES]
        lines.append("  " + " & ".join([label] + cells) + r" \\")
    lines += ["  \\bottomrule", "\\end{tabular}", ""]
    out_path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, dict]] = []
    summary: dict[str, dict] = {}
    for run_dir, short, latex_label in RUNS:
        eval_npz = LOGS_ROOT / run_dir / "eval_multigame.npz"
        if not eval_npz.exists():
            print(f"[fidelity] missing {eval_npz}; skipping {short}")
            continue
        results = _aggregate(eval_npz)
        rows.append((latex_label, results))
        summary[short] = {"run_dir": run_dir, "results": results}
        for algo, label in REGIMES:
            r = results.get(algo)
            if r is None:
                print(f"  {short:6s} {label:24s} no data")
            else:
                print(f"  {short:6s} {label:24s} n={r['n_games']:3d}  "
                      f"mean={100*r['mean']:.2f}%  median={100*r['median']:.2f}%")
    if not rows:
        print("[fidelity] no runs found; nothing written")
        return
    write_table(rows, OUT_DIR / "table.tex")
    (OUT_DIR / "summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\nWrote: {OUT_DIR / 'table.tex'}")
    print(f"       {OUT_DIR / 'summary.json'}")


if __name__ == "__main__":
    main()
