#!/usr/bin/env python3
r"""Generate the main-body in-distribution scaling LaTeX table.

Reads eval_multigame.npz from the three rule-conditional cond_match
runs (Train-14, Train-59, Train-199) — the same checkpoints whose OOD
numbers populate the cond-vs-uncond match table — and emits a row per
preset showing per-cell rollout error under each of the four regimes
(random AR / random TF / BFS oracle / A* oracle).

Output: nca_wm/paper/figures/indist_scaling/{table.tex, summary.json}

Usage:
    .venv/bin/python3 nca_wm/scripts/collate_indist_scaling_table.py
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
LOGS_ROOT = REPO_ROOT / "nca_wm" / "logs"
OUT_DIR = REPO_ROOT / "nca_wm" / "paper" / "figures" / "indist_scaling"

# (run_dir, latex_row_label) — rows follow this order. All three runs
# share the canonical recipe (input_skip + sprite encoder + beta=1.0)
# at 150k updates, differing only in their training preset.
RUNS = [
    ("multi_scaling_14_cond_match_s0",          r"\textsc{Train-14}"),
    ("multi_scaling_gallery_v2_cond_match_s0",  r"\textsc{Train-59}"),
    ("multi_scaling_gallery_v4_cond_match_s0",  r"\textsc{Train-199}"),
]

REGIMES = [
    ("random",    "random (AR)"),
    ("random_tf", "random (TF, 1-step)"),
    ("bfs",       "BFS (oracle)"),
    ("astar",     "A* (oracle)"),
]


_KEY_RE = re.compile(
    r"^(?P<game>.+?)_L(?P<level>\d+)_(?P<algo>random_tf|random|bfs|astar)_cell_error_rate$"
)


def _aggregate(eval_npz: Path) -> dict:
    if not eval_npz.exists():
        raise FileNotFoundError(eval_npz)
    d = np.load(eval_npz, allow_pickle=True)
    per_algo: dict[str, dict[str, list[float]]] = {a: {} for a, _ in REGIMES}
    for key in d.files:
        m = _KEY_RE.match(key)
        if m is None:
            continue
        algo = m.group("algo")
        if algo not in per_algo:
            continue
        arr = np.asarray(d[key], dtype=np.float64).ravel()
        if arr.size == 0:
            continue
        per_algo[algo].setdefault(m.group("game"), []).append(float(arr.mean()))
    out = {}
    for algo, _ in REGIMES:
        per_game_means = [float(np.mean(v)) for v in per_algo[algo].values()]
        if not per_game_means:
            out[algo] = None
        else:
            out[algo] = {
                "n_games": len(per_game_means),
                "mean": float(np.mean(per_game_means)),
                "median": float(np.median(per_game_means)),
            }
    return out


def _fmt(stat: dict | None) -> str:
    if stat is None:
        return "--"
    return f"{100*stat['mean']:.2f} / {100*stat['median']:.2f}"


def write_table(rows: list[tuple[str, dict]], out_path: Path) -> None:
    col_spec = "l " + " ".join(["c"] * len(REGIMES))
    lines = [
        "% AUTOGENERATED by nca_wm/scripts/collate_indist_scaling_table.py — do not edit.",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "  \\toprule",
        "  Preset & " + " & ".join(label for _, label in REGIMES) + r" \\",
        "  & " + " & ".join([r"\small mean / median (\%)"] * len(REGIMES)) + r" \\",
        "  \\midrule",
    ]
    for label, results in rows:
        cells = [_fmt(results.get(algo)) for algo, _ in REGIMES]
        lines.append("  " + " & ".join([label] + cells) + r" \\")
    lines += ["  \\bottomrule", "\\end{tabular}", ""]
    out_path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, dict]] = []
    summary: dict[str, dict] = {}
    for run_dir, latex_label in RUNS:
        eval_npz = LOGS_ROOT / run_dir / "eval_multigame.npz"
        if not eval_npz.exists():
            print(f"[indist-scaling] missing {eval_npz}; skipping {run_dir}")
            continue
        results = _aggregate(eval_npz)
        rows.append((latex_label, results))
        summary[run_dir] = {"latex_label": latex_label, "results": results}
        for algo, label in REGIMES:
            r = results.get(algo)
            if r is None:
                print(f"  {run_dir:42s} {label:24s} no data")
            else:
                print(f"  {run_dir:42s} {label:24s} n={r['n_games']:3d}  "
                      f"mean={100*r['mean']:.2f}%  median={100*r['median']:.2f}%")
    if not rows:
        print("[indist-scaling] no runs found; nothing written")
        return
    write_table(rows, OUT_DIR / "table.tex")
    (OUT_DIR / "summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\nWrote: {OUT_DIR / 'table.tex'}")
    print(f"       {OUT_DIR / 'summary.json'}")


if __name__ == "__main__":
    main()
