#!/usr/bin/env python3
r"""In-distribution dilution table on the 14-game intersection.

Holds the 14 Train-14 games fixed and reports how cell-error on those
same 14 games shifts as the training corpus grows from 14 -> 59 -> 199.
The Train-14 game set is a subset of Train-59 and Train-199, so the
intersection is exactly the Train-14 games (asserted at runtime).

Reads each run's eval_multigame.npz and emits:
  nca_wm/paper/figures/indist_intersection/{table.tex, summary.json}

Run:
    .venv/bin/python3 nca_wm/scripts/collate_indist_intersection.py

Re-run once a missing eval_multigame.npz lands (e.g. the in-flight
multi_scaling_gallery_v4_uncond_match_s0). Missing runs render as "--".
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
LOGS_ROOT = REPO_ROOT / "nca_wm" / "logs"
OUT_DIR = REPO_ROOT / "nca_wm" / "paper" / "figures" / "indist_intersection"

# Column layout: ascending corpus size, with cond/uncond paired at each scale.
RUNS = [
    ("Train-14",  "cond",   "multi_scaling_14_cond_match_s0"),
    ("Train-14",  "uncond", "multi_scaling_14_uncond_match_s0"),
    ("Train-59",  "cond",   "multi_scaling_gallery_v2_cond_match_s0"),
    ("Train-59",  "uncond", "multi_scaling_gallery_v2_uncond_match_s0"),
    ("Train-199", "cond",   "multi_scaling_gallery_v4_cond_match_s0"),
    ("Train-199", "uncond", "multi_scaling_gallery_v4_uncond_match_s0"),
]

# Reported regimes (matching collate_indist_scaling_table.py).
REGIMES = [
    ("random_tf", "1-step (TF)"),
    ("bfs",       "BFS (AR)"),
    ("random",    "random (AR)"),
]
PRIMARY_REGIME = "random_tf"  # the per-game-rows table reports this regime

KEY_RE = re.compile(
    r"^(?P<game>.+?)_L(?P<level>\d+)_(?P<algo>random_tf|random|bfs|astar)_cell_error_rate$"
)


def _per_game(eval_npz: Path) -> dict[str, dict[str, float]]:
    """{game: {algo: mean over levels}} from a single eval_multigame.npz."""
    if not eval_npz.exists():
        return {}
    d = np.load(eval_npz, allow_pickle=True)
    accum: dict[str, dict[str, list[float]]] = {}
    for k in d.files:
        m = KEY_RE.match(k)
        if m is None:
            continue
        algo = m.group("algo")
        arr = np.asarray(d[k], dtype=np.float64).ravel()
        if arr.size == 0:
            continue
        accum.setdefault(m.group("game"), {}).setdefault(algo, []).append(float(arr.mean()))
    return {g: {a: float(np.mean(v)) for a, v in algos.items()} for g, algos in accum.items()}


def _fmt_pct(x: float | None) -> str:
    if x is None or not np.isfinite(x):
        return "--"
    return f"{100*x:.3f}"


def write_table(rows_by_game: list[tuple[str, dict]], aggregates: dict, out_path: Path) -> None:
    """Emit per-game-rows table for the primary regime + aggregate footer.

    Columns: game | T14 cond | T59 cond | T199 cond | T14 uncond | T59 uncond | T199 uncond.
    Aggregate footer rows: mean, median (per-game then averaged across the 14 games).
    """
    col_spec = "l " + " ".join(["c"] * len(RUNS))

    def cell(d: dict, run_dir: str) -> str:
        return _fmt_pct(d.get(run_dir))

    headers = ["Game"] + [f"{p} {m}" for p, m, _ in RUNS]

    lines = [
        "% AUTOGENERATED by nca_wm/scripts/collate_indist_intersection.py -- do not edit.",
        "% Reported regime: 1-step (TF) cell-error, %% per cell, mean across each game's authored levels.",
        "\\begin{adjustbox}{max width=\\linewidth}",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "  \\toprule",
        "  " + " & ".join(headers) + r" \\",
        "  \\midrule",
    ]
    for game, row in rows_by_game:
        cells = [cell(row, r) for _, _, r in RUNS]
        safe_game = game.replace("_", r"\_")
        lines.append("  " + " & ".join([safe_game] + cells) + r" \\")
    lines.append("  \\midrule")
    for stat in ("mean", "median"):
        cells = [_fmt_pct(aggregates[stat][m].get(r)) for _, m, r in RUNS]
        lines.append("  " + " & ".join([f"\\textbf{{{stat}}}"] + cells) + r" \\")
    lines += ["  \\bottomrule", "\\end{tabular}", "\\end{adjustbox}", ""]
    out_path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Load all runs.
    per_run: dict[str, dict[str, dict[str, float]]] = {}
    available: list[str] = []
    missing: list[str] = []
    for _, _, run_dir in RUNS:
        eval_npz = LOGS_ROOT / run_dir / "eval_multigame.npz"
        if eval_npz.exists():
            per_run[run_dir] = _per_game(eval_npz)
            available.append(run_dir)
        else:
            per_run[run_dir] = {}
            missing.append(run_dir)

    # Train-14 cond is the anchor: its 14 games define the intersection.
    anchor = "multi_scaling_14_cond_match_s0"
    if anchor not in available:
        raise SystemExit(f"anchor run {anchor} has no eval_multigame.npz; cannot define intersection")
    intersection = sorted(per_run[anchor].keys())

    # Cross-check that every Train-59 / Train-199 cond run that exists
    # contains the Train-14 games as a subset.
    for run in ("multi_scaling_gallery_v2_cond_match_s0",
                "multi_scaling_gallery_v4_cond_match_s0"):
        if run not in available:
            continue
        missing_in_super = [g for g in intersection if g not in per_run[run]]
        assert not missing_in_super, f"{run} missing games from Train-14: {missing_in_super}"

    # Build per-game rows for the primary regime.
    rows_by_game: list[tuple[str, dict]] = []
    for game in intersection:
        row = {}
        for _, _, run_dir in RUNS:
            v = per_run[run_dir].get(game, {}).get(PRIMARY_REGIME)
            if v is not None:
                row[run_dir] = v
        rows_by_game.append((game, row))

    # Per-run aggregates (mean / median across the 14 intersection games)
    # for every regime.
    aggregates: dict[str, dict[str, dict[str, float]]] = {
        "mean":   {"cond": {}, "uncond": {}},
        "median": {"cond": {}, "uncond": {}},
    }
    summary: dict[str, dict] = {}
    for preset, model, run_dir in RUNS:
        run_summary = {"preset": preset, "model": model, "available": run_dir in available}
        run_summary["regimes"] = {}
        for algo, _label in REGIMES:
            vals = []
            for g in intersection:
                v = per_run[run_dir].get(g, {}).get(algo)
                if v is not None:
                    vals.append(v)
            if vals and len(vals) == len(intersection):
                run_summary["regimes"][algo] = {
                    "n_games": len(vals),
                    "mean":    float(np.mean(vals)),
                    "median":  float(np.median(vals)),
                }
            else:
                run_summary["regimes"][algo] = None
        # Primary regime aggregates feed the table footer.
        head = run_summary["regimes"].get(PRIMARY_REGIME)
        if head is not None:
            aggregates["mean"][model][run_dir]   = head["mean"]
            aggregates["median"][model][run_dir] = head["median"]
        summary[run_dir] = run_summary

    write_table(rows_by_game, aggregates, OUT_DIR / "table.tex")
    (OUT_DIR / "summary.json").write_text(json.dumps({
        "intersection_games": intersection,
        "primary_regime":     PRIMARY_REGIME,
        "runs":               summary,
    }, indent=2))

    # Console report.
    print(f"Intersection: {len(intersection)} games (anchor = {anchor}).")
    print(f"Available runs: {len(available)} / {len(RUNS)}")
    if missing:
        print(f"Missing eval_multigame.npz (rendered as '--'):")
        for r in missing:
            print(f"  {r}")
    print()
    print(f"Primary regime ({PRIMARY_REGIME}) aggregates on the {len(intersection)}-game intersection:")
    print(f"  {'preset/model':<24s}  {'mean':>9s}  {'median':>9s}")
    for preset, model, run_dir in RUNS:
        head = summary[run_dir]["regimes"].get(PRIMARY_REGIME)
        if head is None:
            print(f"  {preset+' '+model:<24s}  {'--':>9s}  {'--':>9s}")
        else:
            print(f"  {preset+' '+model:<24s}  {100*head['mean']:>8.3f}%  {100*head['median']:>8.3f}%")
    print()
    print(f"Wrote: {OUT_DIR/'table.tex'}")
    print(f"       {OUT_DIR/'summary.json'}")


if __name__ == "__main__":
    main()
