#!/usr/bin/env python3
"""Per-rule-type ID error analysis on Train-199.

For each game in Train-199 we (i) parse its .txt for coarse rule-section
features (has_again, has_ellipsis, has_late, has_random, has_dir),
(ii) read its per-level 1-step (TF) cell-error from
  nca_wm/logs/multi_scaling_gallery_v4_<cond|uncond>_match_s0/eval_multigame.npz,
(iii) average across that game's authored levels. We then bucket games by
each feature and report mean cell-error in each bucket for both cond and
uncond, alongside bucket size.

Usage:
    .venv/bin/python3 nca_wm/scripts/rule_type_analysis.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parents[2]

GAME_DIRS = [
    REPO_ROOT / "gallery_games",
    REPO_ROOT / "data" / "scraped_games",
    REPO_ROOT / "data" / "min_games",
    REPO_ROOT / "custom_games",
]

LOG_DIRS = {
    "cond":   REPO_ROOT / "nca_wm" / "logs" / "multi_scaling_gallery_v4_cond_match_s0",
    "uncond": REPO_ROOT / "nca_wm" / "logs" / "multi_scaling_gallery_v4_uncond_match_s0",
}


def find_game_txt(game: str) -> Path | None:
    for d in GAME_DIRS:
        p = d / f"{game}.txt"
        if p.exists():
            return p
    return None


SECTION_HEADERS = ["LEGEND", "SOUNDS", "COLLISIONLAYERS", "RULES",
                   "WINCONDITIONS", "LEVELS"]


def rule_features(path: Path) -> dict[str, bool] | None:
    """Extract coarse rule-section features by regex over the RULES block."""
    s = path.read_text(errors="ignore")
    low = s.lower()
    r_start = low.find("\nrules")
    if r_start < 0:
        return None
    nxt = len(s)
    for h in SECTION_HEADERS:
        if h == "RULES":
            continue
        j = low.find("\n" + h.lower(), r_start + 5)
        if 0 < j < nxt:
            nxt = j
    rules = s[r_start:nxt]
    multi_kernel = False
    for ln in rules.split("\n"):
        if "->" not in ln:
            continue
        lhs = ln.split("->", 1)[0]
        if lhs.count("[") >= 2:
            multi_kernel = True
            break
    return {
        "has_again":        bool(re.search(r"\bagain\b",  rules, re.IGNORECASE)),
        "has_ellipsis":     "..." in rules,
        "has_late":         bool(re.search(r"\blate\b",   rules, re.IGNORECASE)),
        "has_random":       bool(re.search(r"\brandom\b", rules, re.IGNORECASE)),
        "has_dir":          bool(re.search(r"\[\s*[<>^v]", rules, re.IGNORECASE)),
        "has_multi_kernel": multi_kernel,
    }


def per_game_tf(npz_path: Path) -> dict[str, float]:
    """Mean over levels of <game>_L<i>_random_tf_cell_error_rate."""
    if not npz_path.exists():
        return {}
    d = np.load(npz_path, allow_pickle=True)
    pat = re.compile(r"^(?P<g>.+?)_L\d+_random_tf_cell_error_rate$")
    accum: dict[str, list[float]] = {}
    for k in d.files:
        m = pat.match(k)
        if not m:
            continue
        arr = np.asarray(d[k], dtype=np.float64).ravel()
        if arr.size == 0:
            continue
        accum.setdefault(m.group("g"), []).append(float(arr.mean()))
    return {g: float(np.mean(v)) for g, v in accum.items()}


OUT_DIR = REPO_ROOT / "nca_wm" / "paper" / "figures" / "rule_type_analysis"
OUT_TEX = OUT_DIR / "table.tex"
OUT_PDF = OUT_DIR / "rule_type_heatmap.pdf"
OUT_PNG = OUT_DIR / "rule_type_heatmap.png"


def _emit_tex(rows: list[tuple[str, str, int, float, float]]) -> None:
    """rows: (feature, group, n, cond_mean, uncond_mean)."""
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append(r"% AUTOGENERATED by nca_wm/scripts/rule_type_analysis.py -- do not edit.")
    lines.append(r"\begin{tabular}{l l r r r r}")
    lines.append(r"\toprule")
    lines.append(r"feature & group & $n$ & cond & uncond & $\Delta$ \\")
    lines.append(r"\midrule")
    last_feat = None
    for feat, group, n, cm, um in rows:
        if last_feat is not None and feat != last_feat:
            lines.append(r"\midrule")
        feat_str = feat.replace("_", r"\_") if feat != last_feat else ""
        last_feat = feat
        lines.append(
            f"{feat_str} & {group} & {n} & "
            f"{100*cm:.2f}\\% & {100*um:.2f}\\% & "
            f"{100*(um-cm):+.2f}\\% \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    OUT_TEX.write_text("\n".join(lines) + "\n")


FEATURE_LABEL = {
    "has_again":        r"again",
    "has_ellipsis":     r"...",
    "has_late":         r"late",
    "has_random":       r"random",
    "has_dir":          r"dir-prefix",
    "has_multi_kernel": r"multi-kernel",
}


def _emit_heatmap(rows: list[tuple[str, str, int, float, float]]) -> None:
    """5x2 heatmap of yes-bucket cell-error per feature, cond / uncond cols.

    Same log-color idiom as the intersection heatmap so the two read as a
    pair when placed side-by-side in the main body.
    """
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    yes_rows = [(feat, n, cm, um) for (feat, group, n, cm, um) in rows
                if group == "yes"]
    # Sort by max(cond, uncond) descending so the worst feature is at top.
    yes_rows.sort(key=lambda r: -max(r[2], r[3]))

    feats = [r[0] for r in yes_rows]
    ns    = [r[1] for r in yes_rows]
    mat   = np.array([[r[2], r[3]] for r in yes_rows])  # in [0,1]
    matp  = 100 * mat  # percent

    plt.rcParams.update({
        "font.size": 12, "axes.titlesize": 13, "axes.labelsize": 12,
        "xtick.labelsize": 11, "ytick.labelsize": 11, "legend.fontsize": 9,
    })
    # Tuned so that, when scaled to ~0.40 \linewidth in the paper, the
    # heatmap's vertical extent matches the per-game intersection heatmap
    # at ~0.55 \linewidth (intersection figsize 6.4x5.6 → h/w 0.875;
    # target h/w here 1.20 → 3.6 wide × 4.3 tall).
    fig, ax = plt.subplots(figsize=(3.6, 4.3))
    floor = 1e-3
    matrix_log = np.log10(np.clip(matp, floor, None))
    im = ax.imshow(matrix_log, aspect="auto", cmap="magma_r",
                   vmin=np.log10(floor), vmax=np.log10(30.0))

    ax.set_yticks(range(len(feats)))
    ax.set_yticklabels([f"{FEATURE_LABEL[f]} (n={n})" for f, n in zip(feats, ns)])
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["cond", "uncond"], rotation=45,
                       ha="right", rotation_mode="anchor")

    for ri in range(matp.shape[0]):
        for ci in range(matp.shape[1]):
            v = matp[ri, ci]
            text_color = "white" if matrix_log[ri, ci] > np.log10(0.3) else "black"
            ax.text(ci, ri, f"{v:.2f}", ha="center", va="center",
                    fontsize=9, color=text_color)

    cbar = fig.colorbar(im, ax=ax, fraction=0.06, pad=0.03)
    cbar.set_label("cell-error (\\%, log)", fontsize=10)
    log_ticks = [-2, -1, 0, 1]
    cbar.set_ticks(log_ticks)
    cbar.set_ticklabels([f"{10**t:g}" for t in log_ticks])

    fig.tight_layout()
    fig.savefig(OUT_PDF, bbox_inches="tight")
    fig.savefig(OUT_PNG, bbox_inches="tight", dpi=160)
    plt.close(fig)


def main() -> None:
    cond_err   = per_game_tf(LOG_DIRS["cond"]   / "eval_multigame.npz")
    uncond_err = per_game_tf(LOG_DIRS["uncond"] / "eval_multigame.npz")

    games = sorted(set(cond_err) | set(uncond_err))
    print(f"games with at least one model error: {len(games)}", file=sys.stderr)

    feats: dict[str, dict[str, bool] | None] = {}
    for g in games:
        p = find_game_txt(g)
        feats[g] = rule_features(p) if p else None

    n_no_txt = sum(1 for g in games if feats[g] is None)
    if n_no_txt:
        print(f"games without parseable .txt: {n_no_txt}", file=sys.stderr)
    games_with = [g for g in games if feats[g] is not None]

    # n_rules from games_metadata.json for completeness.
    meta = json.loads((REPO_ROOT / "data" / "games_metadata.json").read_text())
    def n_rules(g):
        for cand in (g + ".txt", g.replace(" ", "_") + ".txt", g.lower() + ".txt"):
            if cand in meta:
                return int(meta[cand].get("n_rules", -1))
        return -1

    feature_keys = ["has_again", "has_ellipsis", "has_late", "has_random",
                    "has_dir", "has_multi_kernel"]
    print()
    print(f"{'feature':<14} {'group':<6} {'n':>4} {'cond':>10} {'uncond':>10} {'Δ':>10}")
    print("-" * 60)
    tex_rows: list[tuple[str, str, int, float, float]] = []
    for fk in feature_keys:
        for present in (True, False):
            sub = [g for g in games_with if feats[g][fk] is present]
            if not sub:
                continue
            cs = [cond_err[g]   for g in sub if g in cond_err]
            us = [uncond_err[g] for g in sub if g in uncond_err]
            cm = float(np.mean(cs)) if cs else float("nan")
            um = float(np.mean(us)) if us else float("nan")
            delta = um - cm
            tag = "yes" if present else "no"
            print(f"{fk:<14} {tag:<6} {len(sub):>4} {100*cm:>9.3f}% {100*um:>9.3f}% {100*delta:>+9.3f}%")
            tex_rows.append((fk, tag, len(sub), cm, um))
        print()
    _emit_tex(tex_rows)
    print(f"\nWrote: {OUT_TEX}", file=sys.stderr)
    _emit_heatmap(tex_rows)
    print(f"Wrote: {OUT_PDF}", file=sys.stderr)
    print(f"Wrote: {OUT_PNG}", file=sys.stderr)

    # Rule-count buckets.
    buckets = [(0, 1, "0"), (1, 4, "1-3"), (4, 8, "4-7"), (8, 13, "8-12"), (13, 100, "13+")]
    print(f"{'rule_count':<14} {'n':>4} {'cond':>10} {'uncond':>10} {'Δ':>10}")
    print("-" * 60)
    for lo, hi, tag in buckets:
        sub = [g for g in games_with if lo <= n_rules(g) < hi]
        if not sub:
            continue
        cs = [cond_err[g]   for g in sub if g in cond_err]
        us = [uncond_err[g] for g in sub if g in uncond_err]
        cm = float(np.mean(cs)) if cs else float("nan")
        um = float(np.mean(us)) if us else float("nan")
        print(f"{tag:<14} {len(sub):>4} {100*cm:>9.3f}% {100*um:>9.3f}% {100*(um-cm):>+9.3f}%")


if __name__ == "__main__":
    main()
