"""Validate C++ PuzzleScript engine against solutions generated by NodeJS.

Mirrors the approach in validate_sols.py but validates the C++ engine instead of JAX.
Optionally renders GIFs of JS and C++ replays for visual comparison.
"""
import glob
import json
import math
import os
import sys
import traceback
from typing import List, Optional

import imageio
import numpy as np

# Ensure the project root is on the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from puzzlejax.globals import JS_SOLS_DIR, DATA_DIR, LARK_SYNTAX_PATH
from puzzlejax.preprocessing import get_tree_from_txt, SIMPLIFIED_GAMES_DIR
from puzzlejax.utils import get_list_of_games_for_testing, to_binary_vectors


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------

def _hex_to_rgb(value: str) -> np.ndarray:
    value = value.lstrip("#")
    if len(value) == 3:
        value = "".join(ch * 2 for ch in value)
    return np.array([int(value[i:i + 2], 16) for i in (0, 2, 4)], dtype=np.uint8)


def _get_sprite_specs(js_state) -> list:
    sprites = []
    for obj_name in list(js_state["idDict"]):
        obj = js_state["objects"][obj_name]
        sprite_rows = np.array([list(row) for row in obj["spritematrix"]], dtype=np.int16)
        mask = sprite_rows >= 0
        pixels = np.zeros((*sprite_rows.shape, 3), dtype=np.uint8)
        colors = [_hex_to_rgb(color) for color in list(obj["colors"])]
        for color_idx, color in enumerate(colors):
            pixels[sprite_rows == color_idx] = color
        sprites.append({"pixels": pixels, "mask": mask})
    return sprites


def render_frame_from_objects(objects_flat, width, height, n_objs, sprites, bgcolor):
    """Render a single frame from a flat objects array (JS or C++ format).

    ``objects_flat`` is column-major with ``stride_obj`` int32 words per cell.
    """
    stride_obj = math.ceil(n_objs / 32)
    cell_h, cell_w = sprites[0]["pixels"].shape[:2]
    frame = np.zeros((height * cell_h, width * cell_w, 3), dtype=np.uint8)
    frame[:] = bgcolor

    for x in range(width):
        for y in range(height):
            flat_idx = (x * height + y) * stride_obj
            cell_bits = 0
            for j in range(stride_obj):
                cell_bits |= (int(objects_flat[flat_idx + j]) & 0xFFFFFFFF) << (32 * j)
            if cell_bits == 0:
                continue
            px = x * cell_w
            py = y * cell_h
            for obj_id, sprite in enumerate(sprites):
                if ((cell_bits >> obj_id) & 1) == 0:
                    continue
                alpha_mask = sprite["mask"]
                tile = frame[py:py + cell_h, px:px + cell_w]
                tile[alpha_mask] = sprite["pixels"][alpha_mask]
    return frame


def make_gif(frames, gif_path, scale=1, duration=0.5):
    if scale > 1:
        frames = [
            np.repeat(np.repeat(f, scale, axis=0), scale, axis=1)
            for f in frames
        ]
    gif_dir = os.path.dirname(gif_path)
    if gif_dir:
        os.makedirs(gif_dir, exist_ok=True)
    imageio.mimsave(gif_path, frames, duration=duration, loop=0)


# ---------------------------------------------------------------------------
# Game compile / replay helpers
# ---------------------------------------------------------------------------

def compile_game_for_cpp(js_engine, parser, game):
    """Compile a game via JS and return (game_text, serialized_state_json)."""
    game_path = os.path.join(SIMPLIFIED_GAMES_DIR, f'{game}.txt')
    if not os.path.isfile(game_path):
        get_tree_from_txt(parser=parser, game=game, test_env_init=False, overwrite=True)
    simplified_path = f'{game_path[:-4]}_simplified.txt'
    with open(simplified_path, 'r') as f:
        game_text = f.read()
    js_engine.compile(['restart'], game_text)
    json_str = str(js_engine.serializeCompiledStateJSON())
    return game_text, json_str


def replay_actions_js(js_engine, js_solver, actions, game_text, level_i):
    """Replay actions in JS engine and collect states."""
    js_engine.compile(['loadLevel', level_i], game_text)
    js_states = []
    js_winning = []

    MAX_AGAIN = 50

    # Initial state
    level = js_engine.getLevel()
    js_states.append(list(level['objects']))
    js_winning.append(bool(js_engine.getWinning()))

    for action in actions:
        js_engine.processInput(action)
        ag = 0
        while bool(js_engine.getAgaining()) and ag < MAX_AGAIN:
            js_engine.processInput(-1)
            ag += 1
        level = js_engine.getLevel()
        js_states.append(list(level['objects']))
        js_winning.append(bool(js_engine.getWinning()))

    return js_states, js_winning


def replay_actions_cpp(cpp_engine, serialized_json, actions, level_i):
    """Replay actions in C++ engine and collect states."""
    cpp_engine.load_from_json(serialized_json)
    cpp_engine.load_level(level_i)

    MAX_AGAIN = 50
    cpp_states = []
    cpp_winning = []

    # Initial state
    cpp_states.append(list(cpp_engine.get_objects()))
    cpp_winning.append(cpp_engine.is_winning())

    for action in actions:
        cpp_engine.process_input(action)
        # Handle 'again' ticks
        ag = 0
        while cpp_engine.is_againing() and ag < MAX_AGAIN:
            cpp_engine.process_input(-1)
            ag += 1
        cpp_states.append(list(cpp_engine.get_objects()))
        cpp_winning.append(cpp_engine.is_winning())

    return cpp_states, cpp_winning


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(games: Optional[List[str]] = None, output_dir: str = 'data/cpp_validation_results',
         render: bool = False, render_scale: int = 4, render_mismatches_only: bool = False):
    from javascript import require
    from lark import Lark

    # Load JS engine
    root_dir = os.path.dirname(os.path.abspath(__file__))
    engine_path = os.path.join(root_dir, 'puzzlescript_nodejs', 'puzzlescript', 'engine.js')
    solver_path = os.path.join(root_dir, 'puzzlescript_nodejs', 'puzzlescript', 'solver.js')

    js_engine = require(engine_path)
    js_solver = require(solver_path)

    # Load C++ engine
    import puzzlescript_cpp._puzzlescript_cpp as ps
    cpp_engine = ps.Engine()

    # Load parser
    with open(LARK_SYNTAX_PATH, 'r', encoding='utf-8') as f:
        grammar = f.read()
    parser = Lark(grammar, start='ps_game', maybe_placeholders=False)

    if games is None:
        games = get_list_of_games_for_testing(all_games=True)

    os.makedirs(output_dir, exist_ok=True)

    stats = {
        'total_games': 0,
        'total_levels': 0,
        'success': 0,
        'compile_error': 0,
        'state_mismatch': 0,
        'win_mismatch': 0,
        'runtime_error': 0,
    }
    errors = []

    for game in games:
        stats['total_games'] += 1
        game_name = os.path.basename(game)
        sol_dir = os.path.join(JS_SOLS_DIR, game)

        level_sols = glob.glob(os.path.join(sol_dir, '*level-*.json'))
        if not level_sols:
            print(f"  No solutions for {game_name}, skipping")
            continue

        level_sols = sorted(level_sols, key=lambda p: int(os.path.basename(p).split('-')[-1].split('.')[0]))

        # Compile game
        try:
            game_text, serialized_json = compile_game_for_cpp(js_engine, parser, game)
        except Exception as e:
            stats['compile_error'] += 1
            errors.append({'game': game_name, 'error': 'compile', 'message': str(e)})
            print(f"  Compile error for {game_name}: {e}")
            continue

        # Get rendering info once per game (sprites, bgcolor, n_objs)
        sprites = None
        bgcolor = None
        n_objs = None
        if render:
            try:
                js_state = js_engine.getState()
                sprites = _get_sprite_specs(js_state)
                bgcolor = _hex_to_rgb(js_state["bgcolor"])
                n_objs = len(list(js_state["idDict"]))
            except Exception as e:
                print(f"  Warning: could not load sprites for {game_name}: {e}")
                sprites = None

        print(f"Processing {game_name} ({len(level_sols)} solutions)")

        for sol_path in level_sols:
            sol_filename = os.path.basename(sol_path)
            level_i = int(sol_filename.split('-')[-1].split('.')[0])
            stats['total_levels'] += 1

            try:
                with open(sol_path, 'r') as f:
                    sol_data = json.load(f)

                actions = sol_data.get('actions', sol_data.get('solution', []))
                if isinstance(actions, dict):
                    actions = actions.get('actions', [])

                # Replay in both engines
                js_states, js_winning = replay_actions_js(
                    js_engine, js_solver, actions, game_text, level_i
                )
                cpp_states, cpp_winning = replay_actions_cpp(
                    cpp_engine, serialized_json, actions, level_i
                )

                # Compare states step by step
                mismatch_step = None
                for step in range(min(len(js_states), len(cpp_states))):
                    if js_states[step] != cpp_states[step]:
                        mismatch_step = step
                        break

                is_mismatch = mismatch_step is not None
                is_win_mismatch = js_winning != cpp_winning

                if is_mismatch:
                    stats['state_mismatch'] += 1
                    errors.append({
                        'game': game_name,
                        'level': level_i,
                        'error': 'state_mismatch',
                        'step': mismatch_step,
                    })
                    print(f"  State mismatch at step {mismatch_step} for {game_name} level {level_i}")
                elif is_win_mismatch:
                    stats['win_mismatch'] += 1
                    errors.append({
                        'game': game_name,
                        'level': level_i,
                        'error': 'win_mismatch',
                        'js_winning': js_winning,
                        'cpp_winning': cpp_winning,
                    })
                    print(f"  Win mismatch for {game_name} level {level_i}")
                else:
                    stats['success'] += 1

                # Render GIFs if requested
                should_render = (
                    render and sprites is not None
                    and (not render_mismatches_only or is_mismatch or is_win_mismatch)
                )
                if should_render:
                    width = cpp_engine.get_width()
                    height = cpp_engine.get_height()
                    game_gif_dir = os.path.join(output_dir, game_name)
                    os.makedirs(game_gif_dir, exist_ok=True)

                    def _frames_from_states(states):
                        return [
                            render_frame_from_objects(s, width, height, n_objs, sprites, bgcolor)
                            for s in states
                        ]

                    # JS GIF
                    js_gif_path = os.path.join(game_gif_dir, f'level-{level_i}_js.gif')
                    make_gif(_frames_from_states(js_states), js_gif_path,
                             scale=render_scale, duration=0.5)

                    # C++ GIF
                    cpp_gif_path = os.path.join(game_gif_dir, f'level-{level_i}_cpp.gif')
                    make_gif(_frames_from_states(cpp_states), cpp_gif_path,
                             scale=render_scale, duration=0.5)

                    # Side-by-side comparison GIF
                    js_frames = _frames_from_states(js_states)
                    cpp_frames = _frames_from_states(cpp_states)
                    max_len = max(len(js_frames), len(cpp_frames))
                    # Pad shorter sequence by repeating last frame
                    while len(js_frames) < max_len:
                        js_frames.append(js_frames[-1])
                    while len(cpp_frames) < max_len:
                        cpp_frames.append(cpp_frames[-1])
                    separator_w = 2
                    combo_frames = []
                    for jf, cf in zip(js_frames, cpp_frames):
                        jh, jw = jf.shape[:2]
                        ch, cw = cf.shape[:2]
                        h = max(jh, ch)
                        # Pad vertically if heights differ
                        if jh < h:
                            jf = np.pad(jf, ((0, h - jh), (0, 0), (0, 0)))
                        if ch < h:
                            cf = np.pad(cf, ((0, h - ch), (0, 0), (0, 0)))
                        sep = np.full((h, separator_w, 3), 128, dtype=np.uint8)
                        combo_frames.append(np.concatenate([jf, sep, cf], axis=1))
                    combo_gif_path = os.path.join(game_gif_dir, f'level-{level_i}_compare.gif')
                    make_gif(combo_frames, combo_gif_path,
                             scale=render_scale, duration=0.5)
                    print(f"    Rendered level {level_i} GIFs to {game_gif_dir}")

            except Exception as e:
                stats['runtime_error'] += 1
                errors.append({
                    'game': game_name,
                    'level': level_i,
                    'error': 'runtime',
                    'message': traceback.format_exc(),
                })
                print(f"  Runtime error for {game_name} level {level_i}: {e}")

    # Save results
    results = {'stats': stats, 'errors': errors}
    results_path = os.path.join(output_dir, 'validation_results.json')
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=2)

    print(f"\n{'='*60}")
    print(f"Validation Results:")
    print(f"  Total games:      {stats['total_games']}")
    print(f"  Total levels:     {stats['total_levels']}")
    print(f"  Success:          {stats['success']}")
    print(f"  Compile errors:   {stats['compile_error']}")
    print(f"  State mismatches: {stats['state_mismatch']}")
    print(f"  Win mismatches:   {stats['win_mismatch']}")
    print(f"  Runtime errors:   {stats['runtime_error']}")
    print(f"{'='*60}")

    return results


if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser(description='Validate C++ PuzzleScript engine')
    ap.add_argument('--game', type=str, default=None, help='Validate a single game')
    ap.add_argument('--games', type=str, nargs='+', default=None, help='Validate specific games')
    ap.add_argument('--output-dir', type=str, default='data/cpp_validation_results')
    ap.add_argument('--render', action='store_true', help='Render GIFs of JS and C++ replays')
    ap.add_argument('--render-scale', type=int, default=4, help='Pixel scale factor for GIFs')
    ap.add_argument('--render-mismatches-only', action='store_true',
                    help='Only render GIFs for levels with mismatches')
    args = ap.parse_args()

    if args.game:
        game_list = [args.game]
    elif args.games:
        game_list = args.games
    else:
        game_list = None

    main(games=game_list, output_dir=args.output_dir,
         render=args.render, render_scale=args.render_scale,
         render_mismatches_only=args.render_mismatches_only)
