"""Validate C++ PuzzleScript engine against solutions generated by NodeJS.

Mirrors the approach in validate_sols.py but validates the C++ engine instead of JAX.
"""
import glob
import json
import os
import sys
import traceback
from typing import List, Optional

import numpy as np

# Ensure the project root is on the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from puzzlejax.globals import JS_SOLS_DIR, DATA_DIR, LARK_SYNTAX_PATH
from puzzlejax.preprocessing import get_tree_from_txt, SIMPLIFIED_GAMES_DIR
from puzzlejax.utils import get_list_of_games_for_testing, to_binary_vectors


def compile_game_for_cpp(js_engine, parser, game):
    """Compile a game via JS and return (game_text, serialized_state_json)."""
    game_path = os.path.join(SIMPLIFIED_GAMES_DIR, f'{game}.txt')
    if not os.path.isfile(game_path):
        get_tree_from_txt(parser=parser, game=game, test_env_init=False, overwrite=True)
    simplified_path = f'{game_path[:-4]}_simplified.txt'
    with open(simplified_path, 'r') as f:
        game_text = f.read()
    js_engine.compile(['restart'], game_text)
    serialized = js_engine.serializeCompiledState()
    # Convert JS proxy to proper JSON string
    json_str = json.dumps(serialized)
    return game_text, json_str


def replay_actions_js(js_engine, js_solver, actions, game_text, level_i):
    """Replay actions in JS engine and collect states."""
    js_engine.compile(['loadLevel', level_i], game_text)
    js_solver.precalcDistances(js_engine)
    js_states = []
    js_winning = []

    # Initial state
    state_data = js_engine.getState()
    level = js_engine.getLevel()
    js_states.append(list(level['objects']))
    js_winning.append(bool(js_engine.getWinning()))

    for action in actions:
        result = js_solver.takeAction(js_engine, action)
        level = js_engine.getLevel()
        js_states.append(list(level['objects']))
        js_winning.append(bool(js_engine.getWinning()))

    return js_states, js_winning


def replay_actions_cpp(cpp_engine, serialized_json, actions, level_i):
    """Replay actions in C++ engine and collect states."""
    cpp_engine.load_from_json(serialized_json)
    cpp_engine.load_level(level_i)

    cpp_states = []
    cpp_winning = []

    # Initial state
    cpp_states.append(list(cpp_engine.get_objects()))
    cpp_winning.append(cpp_engine.winning)

    for action in actions:
        cpp_engine.process_input(action)
        # Handle 'again' ticks
        while cpp_engine.againing:
            cpp_engine.process_input(-1)
        cpp_states.append(list(cpp_engine.get_objects()))
        cpp_winning.append(cpp_engine.winning)

    return cpp_states, cpp_winning


def main(games: Optional[List[str]] = None, output_dir: str = 'data/cpp_validation_results'):
    from javascript import require
    from lark import Lark

    # Load JS engine
    root_dir = os.path.dirname(os.path.abspath(__file__))
    engine_path = os.path.join(root_dir, 'puzzlescript_nodejs', 'puzzlescript', 'engine.js')
    solver_path = os.path.join(root_dir, 'puzzlescript_nodejs', 'puzzlescript', 'solver.js')

    js_engine = require(engine_path)
    js_solver = require(solver_path)

    # Load C++ engine
    from puzzlescript_cpp import CppPuzzleScriptEngine
    cpp_engine = CppPuzzleScriptEngine()

    # Load parser
    with open(LARK_SYNTAX_PATH, 'r', encoding='utf-8') as f:
        grammar = f.read()
    parser = Lark(grammar, start='ps_game', maybe_placeholders=False)

    if games is None:
        games = get_list_of_games_for_testing(all_games=True)

    os.makedirs(output_dir, exist_ok=True)

    stats = {
        'total_games': 0,
        'total_levels': 0,
        'success': 0,
        'compile_error': 0,
        'state_mismatch': 0,
        'win_mismatch': 0,
        'runtime_error': 0,
    }
    errors = []

    for game in games:
        stats['total_games'] += 1
        game_name = os.path.basename(game)
        sol_dir = os.path.join(JS_SOLS_DIR, game)

        level_sols = glob.glob(os.path.join(sol_dir, '*level-*.json'))
        if not level_sols:
            print(f"  No solutions for {game_name}, skipping")
            continue

        level_sols = sorted(level_sols, key=lambda p: int(os.path.basename(p).split('-')[-1].split('.')[0]))

        # Compile game
        try:
            game_text, serialized_json = compile_game_for_cpp(js_engine, parser, game)
        except Exception as e:
            stats['compile_error'] += 1
            errors.append({'game': game_name, 'error': 'compile', 'message': str(e)})
            print(f"  Compile error for {game_name}: {e}")
            continue

        print(f"Processing {game_name} ({len(level_sols)} solutions)")

        for sol_path in level_sols:
            sol_filename = os.path.basename(sol_path)
            level_i = int(sol_filename.split('-')[-1].split('.')[0])
            stats['total_levels'] += 1

            try:
                with open(sol_path, 'r') as f:
                    sol_data = json.load(f)

                actions = sol_data.get('actions', sol_data.get('solution', []))
                if isinstance(actions, dict):
                    actions = actions.get('actions', [])

                # Replay in both engines
                js_states, js_winning = replay_actions_js(
                    js_engine, js_solver, actions, game_text, level_i
                )
                cpp_states, cpp_winning = replay_actions_cpp(
                    cpp_engine, serialized_json, actions, level_i
                )

                # Compare states step by step
                mismatch_step = None
                for step in range(min(len(js_states), len(cpp_states))):
                    if js_states[step] != cpp_states[step]:
                        mismatch_step = step
                        break

                if mismatch_step is not None:
                    stats['state_mismatch'] += 1
                    errors.append({
                        'game': game_name,
                        'level': level_i,
                        'error': 'state_mismatch',
                        'step': mismatch_step,
                    })
                    print(f"  State mismatch at step {mismatch_step} for {game_name} level {level_i}")
                    continue

                # Compare win states
                if js_winning != cpp_winning:
                    stats['win_mismatch'] += 1
                    errors.append({
                        'game': game_name,
                        'level': level_i,
                        'error': 'win_mismatch',
                        'js_winning': js_winning,
                        'cpp_winning': cpp_winning,
                    })
                    print(f"  Win mismatch for {game_name} level {level_i}")
                    continue

                stats['success'] += 1

            except Exception as e:
                stats['runtime_error'] += 1
                errors.append({
                    'game': game_name,
                    'level': level_i,
                    'error': 'runtime',
                    'message': traceback.format_exc(),
                })
                print(f"  Runtime error for {game_name} level {level_i}: {e}")

    # Save results
    results = {'stats': stats, 'errors': errors}
    results_path = os.path.join(output_dir, 'validation_results.json')
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=2)

    print(f"\n{'='*60}")
    print(f"Validation Results:")
    print(f"  Total games:      {stats['total_games']}")
    print(f"  Total levels:     {stats['total_levels']}")
    print(f"  Success:          {stats['success']}")
    print(f"  Compile errors:   {stats['compile_error']}")
    print(f"  State mismatches: {stats['state_mismatch']}")
    print(f"  Win mismatches:   {stats['win_mismatch']}")
    print(f"  Runtime errors:   {stats['runtime_error']}")
    print(f"{'='*60}")

    return results


if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser(description='Validate C++ PuzzleScript engine')
    ap.add_argument('--game', type=str, default=None, help='Validate a single game')
    ap.add_argument('--games', type=str, nargs='+', default=None, help='Validate specific games')
    ap.add_argument('--output-dir', type=str, default='data/cpp_validation_results')
    args = ap.parse_args()

    if args.game:
        game_list = [args.game]
    elif args.games:
        game_list = args.games
    else:
        game_list = None

    main(games=game_list, output_dir=args.output_dir)
