"""
Run a simple (lambda + mu) evolutionary search over PuzzleScript mutants
generated by a trained diff language model.

Usage:
    python mutate_and_solve.py --model_dir models/diff_lm/final --n_generations 10 --lambda_size 4 --mu 2
    python mutate_and_solve.py --model_dir models/diff_lm/final --n_generations 10 --lambda_size 4 --mu 2 --no_vllm
    python mutate_and_solve.py --game_file data/scraped_games/sokoban_basic.txt
"""

import argparse
import glob
import json
import os
import random
import re
import subprocess
import tempfile
from pathlib import Path

BOS_BEFORE = "<|before|>"
BOS_DIFF = "<|diff|>"
EOS_DIFF = "<|enddiff|>"

DEFAULT_GAME_FILE = os.path.join("data", "scraped_games", "sokoban_basic.txt")
DEFAULT_MODEL_DIR = os.path.join("models", "diff_lm", "final")
OUTPUT_DIR = os.path.join("data", "diff_mutations")

_backend = None
_tokenizer = None
_model = None
_vllm_model = None


def get_backend():
    global _backend
    if _backend is None:
        from backends.nodejs import NodeJSPuzzleScriptBackend
        _backend = NodeJSPuzzleScriptBackend()
    return _backend


def load_model_vllm(model_dir: str):
    global _vllm_model
    if _vllm_model is None:
        from vllm import LLM
        _vllm_model = LLM(model=model_dir, dtype="float16", max_model_len=1024)
    return _vllm_model


def load_model_hf(model_dir: str):
    global _tokenizer, _model
    if _model is None:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer

        _tokenizer = AutoTokenizer.from_pretrained(model_dir)
        _model = AutoModelForCausalLM.from_pretrained(model_dir)
        if torch.cuda.is_available():
            _model = _model.cuda().half()
        _model.eval()
    return _tokenizer, _model


def load_game(game_file: str) -> tuple[str, str]:
    with open(game_file, "r", encoding="utf-8", errors="replace") as f:
        return game_file, f.read()


def resolve_model_dir(model_dir: str) -> str:
    if os.path.isdir(model_dir):
        return model_dir

    if os.path.normpath(model_dir) != os.path.normpath(DEFAULT_MODEL_DIR):
        raise FileNotFoundError(f"Model directory not found: {model_dir}")

    checkpoint_glob = os.path.join(os.path.dirname(DEFAULT_MODEL_DIR), "checkpoint-*")
    checkpoints = [path for path in glob.glob(checkpoint_glob) if os.path.isdir(path)]
    if not checkpoints:
        raise FileNotFoundError(
            f"Model directory not found: {model_dir}. No fallback checkpoints found in "
            f"{os.path.dirname(DEFAULT_MODEL_DIR)}"
        )

    latest_checkpoint = max(checkpoints, key=os.path.getmtime)
    print(f"Model directory {model_dir} not found; using latest checkpoint {latest_checkpoint}")
    return latest_checkpoint


def build_source_prompt(game_text: str, tokenizer=None, max_prompt_tokens: int = 512) -> str:
    source = game_text if game_text.endswith("\n") else game_text + "\n"
    if tokenizer is not None:
        overhead_str = f"{BOS_BEFORE}\n\n{BOS_DIFF}\n"
        overhead = len(tokenizer.encode(overhead_str, add_special_tokens=False))
        budget = max_prompt_tokens - overhead
        if budget < 50:
            budget = 50
        source_ids = tokenizer.encode(source, add_special_tokens=False)
        if len(source_ids) > budget:
            raise ValueError(
                f"Source file is too long for the prompt budget: "
                f"{len(source_ids)} tokens > {budget} tokens available "
                f"(max_prompt_tokens={max_prompt_tokens})"
            )
    return f"{BOS_BEFORE}\n{source.rstrip()}\n{BOS_DIFF}\n"


def generate_diff_vllm(model_dir: str, prompt: str, temperature: float = 0.8, max_tokens: int = 256) -> str:
    from vllm import SamplingParams

    llm = load_model_vllm(model_dir)
    params = SamplingParams(
        temperature=temperature,
        max_tokens=max_tokens,
        stop=[EOS_DIFF],
        top_p=0.95,
    )
    outputs = llm.generate([prompt], params)
    return outputs[0].outputs[0].text


def generate_diff_hf(model_dir: str, prompt: str, temperature: float = 0.8, max_tokens: int = 256) -> str:
    import torch

    tokenizer, model = load_model_hf(model_dir)
    inputs = tokenizer(prompt, return_tensors="pt", truncation=False)
    if torch.cuda.is_available():
        inputs = {k: v.cuda() for k, v in inputs.items()}

    eos_diff_id = tokenizer.convert_tokens_to_ids(EOS_DIFF)
    eos_ids = [tokenizer.eos_token_id]
    if eos_diff_id != tokenizer.unk_token_id:
        eos_ids.append(eos_diff_id)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=temperature,
            top_p=0.95,
            do_sample=True,
            eos_token_id=eos_ids,
            pad_token_id=tokenizer.pad_token_id,
        )
    generated = output_ids[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(generated, skip_special_tokens=False).split(EOS_DIFF)[0]


def apply_unified_diff(original_text: str, diff_text: str) -> str | None:
    with tempfile.TemporaryDirectory() as tmpdir:
        game_dir = os.path.join(tmpdir, "clean_data")
        os.makedirs(game_dir, exist_ok=True)
        orig_path = os.path.join(game_dir, "game.txt")

        with open(orig_path, "w", encoding="utf-8") as f:
            f.write(original_text)

        diff_lines = diff_text.strip().splitlines(keepends=True)
        normalized = []
        for line in diff_lines:
            if line.startswith("--- "):
                normalized.append("--- clean_data/game.txt\n")
            elif line.startswith("+++ "):
                normalized.append("+++ clean_data/game.txt\n")
            else:
                normalized.append(line if line.endswith("\n") else line + "\n")
        diff_path = os.path.join(tmpdir, "mutation.diff")
        with open(diff_path, "w", encoding="utf-8") as f:
            f.write("".join(normalized))

        subprocess.run(
            ["patch", "--no-backup-if-mismatch", "-p0", "-l", "-f", "--fuzz=3", "-i", diff_path],
            capture_output=True,
            text=True,
            cwd=tmpdir,
            timeout=10,
        )

        try:
            with open(orig_path, "r", encoding="utf-8") as f:
                return f.read()
        except FileNotFoundError:
            return None


def apply_diff_manual(original_text: str, diff_text: str) -> str | None:
    orig_lines = original_text.splitlines(keepends=True)
    result_lines = list(orig_lines)
    hunk_pattern = re.compile(r"^@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@")
    diff_lines = diff_text.splitlines(keepends=True)

    i = 0
    offset = 0
    while i < len(diff_lines):
        match = hunk_pattern.match(diff_lines[i])
        if not match:
            i += 1
            continue

        orig_start = int(match.group(1)) - 1
        i += 1
        pos = orig_start + offset
        while i < len(diff_lines):
            line = diff_lines[i]
            if line.startswith("@@") or line.startswith("---") or line.startswith("+++"):
                break
            if line.startswith("-"):
                if pos < len(result_lines):
                    result_lines.pop(pos)
                    offset -= 1
                i += 1
            elif line.startswith("+"):
                result_lines.insert(pos, line[1:])
                pos += 1
                offset += 1
                i += 1
            elif line.startswith(" ") or line.strip() == "":
                pos += 1
                i += 1
            else:
                i += 1

    if not result_lines:
        return None
    return "".join(result_lines)


def get_num_levels(game_text: str) -> int | None:
    backend = get_backend()
    try:
        backend.unload_game()
        backend.load_level(game_text, 0)
        return backend.engine.getNumLevels()
    except Exception:
        return None


def solve_game(game_text: str, level_i: int = 0, algo: str = "astar", n_steps: int = 5000, timeout_ms: int = 10000) -> dict:
    backend = get_backend()
    try:
        backend.unload_game()
        result = backend.run_search(
            algo,
            game_text=game_text,
            level_i=level_i,
            n_steps=n_steps,
            timeout_ms=timeout_ms,
        )
        return {
            "solved": result.solved,
            "actions": list(result.actions),
            "time": result.time,
            "iterations": result.iterations,
            "score": result.score,
            "timeout": result.timeout,
        }
    except Exception as e:
        return {"solved": False, "error": str(e)}


def render_solution_gif(game_text: str, actions: list[int], gif_path: str, level_i: int = 0, frame_duration_s: float = 0.3) -> str | None:
    backend = get_backend()
    try:
        return backend.render_gif(
            game_text=game_text,
            level_i=level_i,
            actions=actions,
            gif_path=gif_path,
            frame_duration_s=frame_duration_s,
        )
    except Exception as e:
        print(f"  Render error: {e}")
        return None


def generate_mutation(*, parent_text: str, model_dir: str, prompt_tokenizer, generate_fn, temperature: float, max_tokens: int) -> tuple[str | None, str | None, str | None]:
    max_prompt_tokens = 1024 - max_tokens
    try:
        prompt = build_source_prompt(parent_text, tokenizer=prompt_tokenizer, max_prompt_tokens=max_prompt_tokens)
    except ValueError as e:
        return None, None, f"prompt_build: {e}"

    diff_output = generate_fn(model_dir, prompt, temperature=temperature, max_tokens=max_tokens)
    mutated = apply_diff_manual(parent_text, diff_output)
    if mutated is None or mutated.strip() == parent_text.strip():
        mutated = apply_unified_diff(parent_text, f"--- a/game.txt\n+++ b/game.txt\n{diff_output}")
    if mutated is None or len(mutated.strip()) < 10:
        return diff_output, None, "diff_apply_failed"
    return diff_output, mutated, None


def evaluate_mutant(*, mutated_text: str, mutation_id: str, generation: int, parent_id: str, diff_output: str, run_dir: str, algo: str, n_steps: int, timeout_ms: int) -> dict:
    mut_filename = f"{mutation_id}.txt"
    diff_filename = f"{mutation_id}.diff"
    with open(os.path.join(run_dir, mut_filename), "w", encoding="utf-8") as f:
        f.write(mutated_text)
    with open(os.path.join(run_dir, diff_filename), "w", encoding="utf-8") as f:
        f.write(diff_output)

    n_levels_found = get_num_levels(mutated_text)
    entry = {
        "id": mutation_id,
        "generation": generation,
        "parent_id": parent_id,
        "game_file": mut_filename,
        "diff_file": diff_filename,
        "compiled": bool(n_levels_found and n_levels_found > 0),
        "fitness": 1 if n_levels_found and n_levels_found > 0 else 0,
        "levels": [],
        "text": mutated_text,
    }
    if not entry["compiled"]:
        return entry

    entry["n_levels"] = n_levels_found
    all_levels_solved = True
    for level_i in range(n_levels_found):
        sol = solve_game(mutated_text, level_i=level_i, algo=algo, n_steps=n_steps, timeout_ms=timeout_ms)
        level_entry = {"level": level_i}
        if "error" not in sol:
            gif_name = None
            rendered = None
            if sol["actions"]:
                gif_name = f"{mutation_id}_level_{level_i:03d}_sol.gif"
                gif_path = os.path.join(run_dir, gif_name)
                rendered = render_solution_gif(mutated_text, sol["actions"], gif_path, level_i=level_i)
            level_entry.update({
                "solved": sol.get("solved"),
                "actions": sol["actions"],
                "time": sol["time"],
                "iterations": sol["iterations"],
                "score": sol.get("score"),
                "timeout": sol.get("timeout"),
                "gif": gif_name if rendered else None,
            })
            if not sol.get("solved"):
                all_levels_solved = False
        else:
            all_levels_solved = False
            level_entry.update({"solved": False, "reason": sol["error"]})
        entry["levels"].append(level_entry)
    entry["solved"] = all_levels_solved
    return entry


def select_next_population(population: list[dict], mu: int) -> list[dict]:
    ranked = sorted(
        population,
        key=lambda cand: (
            cand["fitness"],
            cand.get("compiled", False),
            cand.get("solved", False),
            cand.get("generation", -1),
        ),
        reverse=True,
    )
    return ranked[:mu]


def run_mutation_loop(
    model_dir: str,
    game_file: str = DEFAULT_GAME_FILE,
    n_generations: int = 10,
    lambda_size: int = 4,
    mu: int = 2,
    use_vllm: bool = True,
    algo: str = "astar",
    n_steps: int = 5000,
    timeout_ms: int = 10000,
    temperature: float = 0.8,
    max_tokens: int = 256,
    output_dir: str = OUTPUT_DIR,
):
    model_dir = resolve_model_dir(model_dir)
    os.makedirs(output_dir, exist_ok=True)
    generate_fn = generate_diff_vllm if use_vllm else generate_diff_hf

    from transformers import AutoTokenizer
    prompt_tokenizer = AutoTokenizer.from_pretrained(model_dir)

    game_path, game_text = load_game(game_file)
    game_name = Path(game_path).stem
    print(f"Base game: {game_name} ({len(game_text)} chars)")

    run_dir = os.path.join(output_dir, game_name)
    os.makedirs(run_dir, exist_ok=True)
    with open(os.path.join(run_dir, "original.txt"), "w", encoding="utf-8") as f:
        f.write(game_text)

    base_n_levels = get_num_levels(game_text)
    population = [{
        "id": "parent_000",
        "generation": -1,
        "parent_id": None,
        "game_file": "original.txt",
        "diff_file": None,
        "compiled": bool(base_n_levels),
        "fitness": 1 if base_n_levels else 0,
        "levels": [],
        "solved": False,
        "text": game_text,
    }]
    results = []
    mutation_counter = 0

    for generation in range(n_generations):
        print(f"\n=== Generation {generation + 1}/{n_generations} ===")
        offspring = []
        for child_idx in range(lambda_size):
            parent = random.choice(population)
            mutation_id = f"mutation_{mutation_counter:03d}"
            mutation_counter += 1
            print(f"  Offspring {child_idx + 1}/{lambda_size}: parent={parent['id']} fitness={parent['fitness']}")
            try:
                diff_output, mutated_text, error = generate_mutation(
                    parent_text=parent["text"],
                    model_dir=model_dir,
                    prompt_tokenizer=prompt_tokenizer,
                    generate_fn=generate_fn,
                    temperature=temperature,
                    max_tokens=max_tokens,
                )
            except Exception as e:
                diff_output, mutated_text, error = None, None, f"generation: {e}"

            if error is not None:
                print(f"    Rejected: {error}")
                entry = {
                    "id": mutation_id,
                    "generation": generation,
                    "parent_id": parent["id"],
                    "compiled": False,
                    "fitness": 0,
                    "error": error,
                    "diff_file": None,
                    "game_file": None,
                }
                if diff_output is not None:
                    diff_filename = f"{mutation_id}.diff"
                    with open(os.path.join(run_dir, diff_filename), "w", encoding="utf-8") as f:
                        f.write(diff_output)
                    entry["diff_file"] = diff_filename
                results.append(entry)
                offspring.append(entry)
                continue

            print(f"    Generated {len(diff_output)} chars of diff")
            entry = evaluate_mutant(
                mutated_text=mutated_text,
                mutation_id=mutation_id,
                generation=generation,
                parent_id=parent["id"],
                diff_output=diff_output,
                run_dir=run_dir,
                algo=algo,
                n_steps=n_steps,
                timeout_ms=timeout_ms,
            )
            if entry["compiled"]:
                print(f"    Compiled: fitness=1, levels={entry['n_levels']}")
            else:
                print("    Failed to compile: fitness=0")
            results.append({k: v for k, v in entry.items() if k != "text"})
            offspring.append(entry)

        population = select_next_population(population + offspring, mu)
        print("  Survivors: " + ", ".join(f"{cand['id']}[fit={cand['fitness']}]" for cand in population))

    summary_path = os.path.join(run_dir, "results.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    attempted = sum(1 for r in results if r.get("generation", -1) >= 0)
    compiled = sum(1 for r in results if r.get("generation", -1) >= 0 and r.get("compiled"))
    solved_mutants = sum(1 for r in results if r.get("solved"))
    total_levels = sum(len(r.get("levels", [])) for r in results if r.get("compiled"))
    solved_levels = sum(
        sum(1 for level in r.get("levels", []) if level.get("solved"))
        for r in results if r.get("compiled")
    )
    print(f"\n=== Summary ===")
    print(f"Generations: {n_generations}")
    print(f"Offspring attempted: {attempted}")
    print(f"Compiled successfully: {compiled}/{attempted}")
    print(f"Mutants with all levels solved: {solved_mutants}/{attempted}")
    print(f"Levels solved: {solved_levels}/{total_levels}")
    print("Final population: " + ", ".join(f"{cand['id']}[fit={cand['fitness']}]" for cand in population))
    print(f"Results saved to: {run_dir}")
    return results


def main():
    parser = argparse.ArgumentParser(description="Mutate PuzzleScript games with a diff LM")
    parser.add_argument("--model_dir", type=str, default=DEFAULT_MODEL_DIR, help="Path to trained model")
    parser.add_argument("--game_file", type=str, default=DEFAULT_GAME_FILE, help="Specific game file to mutate")
    parser.add_argument("--n_generations", type=int, default=10, help="Number of evolutionary generations")
    parser.add_argument("--lambda_size", type=int, default=4, help="Number of offspring to generate per generation")
    parser.add_argument("--mu", type=int, default=2, help="Number of survivors kept after each generation")
    parser.add_argument("--no_vllm", action="store_true", help="Use HuggingFace transformers instead of vLLM")
    parser.add_argument("--algo", type=str, default="astar", choices=["bfs", "astar", "gbfs"], help="Search algorithm for solving")
    parser.add_argument("--n_steps", type=int, default=5000, help="Max search steps")
    parser.add_argument("--timeout_ms", type=int, default=10000, help="Search timeout in milliseconds")
    parser.add_argument("--temperature", type=float, default=0.8, help="Sampling temperature for diff generation")
    parser.add_argument("--max_tokens", type=int, default=256, help="Max tokens to generate per diff")
    parser.add_argument("--output_dir", type=str, default=OUTPUT_DIR)
    parser.add_argument("--seed", type=int, default=None, help="Random seed")
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    run_mutation_loop(
        model_dir=args.model_dir,
        game_file=args.game_file,
        n_generations=args.n_generations,
        lambda_size=args.lambda_size,
        mu=args.mu,
        use_vllm=not args.no_vllm,
        algo=args.algo,
        n_steps=args.n_steps,
        timeout_ms=args.timeout_ms,
        temperature=args.temperature,
        max_tokens=args.max_tokens,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    main()
