defaults:
  - train_config
  - _self_

  # - override hydra/launcher: basic
  # - override hydra/launcher: submitit_local
  - override hydra/launcher: submitit_slurm

hydra:
  verbose: true
  sweeper:
    params:

  launcher:
    tasks_per_node: 1
    cpus_per_task: 1
    gpus_per_node: 1
    timeout_min: 1440
    mem_gb: 30
    account: pr_174_tandon_advanced
